apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-mottak
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: 3000ms
spec:
  image: "{{image}}"
  port: 8080
  strategy:
    type: RollingUpdate # Bruk kun Recreate når vi deployer store/ukompatible migreringer
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: "java"
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: "{{kafka_pool}}"
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "4edb2ce5-4f0e-4f6f-9b82-b8e75e9dd09e"
  env:
    - name: DP_PROXY_HOST
      value: "{{dp_proxy.ingress}}"
    - name: PDL_API_HOST
      value: "{{pdl.ingress}}"
    - name: DOKARKIV_INGRESS
      value: "{{dokarkiv.ingress}}"
    - name: OPPGAVE_SCOPE
      value: "{{oppgave.scope}}"
    - name: OPPGAVE_URL
      value: "{{oppgave.ingress}}"
    - name: SAF_URL
      value: "{{saf.ingress}}"
    - name: SAF_SCOPE
      value: "{{saf.scope}}"
  envFrom:
    - secret: dp-mottak-unleash-api-token
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: skjermede-personer-pip
          namespace: nom
        - application: "{{ oppgave.app }}"
          namespace: oppgavehandtering
        - application: "{{ saf.app }}"
          namespace: teamdokumenthandtering
        - application: dp-saksbehandling
      external:
        - host: "{{dp_proxy.ingress}}"
        - host: "{{pdl.ingress}}"
        - host: "{{dokarkiv.ingress}}"
        - host: teamdagpenger-unleash-api.nav.cloud.nais.io
  {{#if ingresses}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  {{/if}}
  gcp:
    sqlInstances:
      - name: dp-mottak
        type: POSTGRES_16
        tier:  "{{db_tier}}"
        diskType: SSD
        highAvailability: true
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: mottak
            envVarPrefix: DB
            users:
              - name: bqconn_dataanalyse
        cascadingDelete: false
        pointInTimeRecovery: true
        retainedBackups: {{point_in_time_recovery_days}}
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
