apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-mottak
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "4edb2ce5-4f0e-4f6f-9b82-b8e75e9dd09e"
  env:
    - name: DP_PROXY_HOST
      value: {{dp_proxy.ingress}}
    - name: PDL_API_HOST
      value: {{pdl.ingress}}
    - name: DOKARKIV_INGRESS
      value: {{dokarkiv.ingress}}
  accessPolicy:
    outbound:
      rules:
       - application: skjermede-personer-pip
         namespace: nom
       - application: dp-regel-api
      external:
        - host: {{dp_proxy.ingress}}
        - host: {{pdl.ingress}}
        - host: {{dokarkiv.ingress}}
    inbound:
      rules:
        - application: dp-quiz-retting
  {{#if ingresses}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  {{/if}}
  gcp:
    sqlInstances:
      - name: dp-mottak
        type: POSTGRES_12
        tier:  {{db_tier}}
        diskType: SSD
        highAvailability: false
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: mottak
            envVarPrefix: DB
            users:
              - name: bqconn_dataanalyse
        cascadingDelete: false
        pointInTimeRecovery: true
        retainedBackups: {{point_in_time_recovery_days}}
