app: dp-mottak
kafka_pool: nav-prod
db_tier: db-custom-4-15360
db_size: 1000
replicas_min: 2
replicas_max: 6
point_in_time_recovery_days: 14
dp_proxy:
  ingress: dp-proxy.prod-fss-pub.nais.io
pdl:
  ingress: pdl-api.prod-fss-pub.nais.io
dokarkiv:
  ingress: dokarkiv.dev-fss-pub.nais.io