@startuml
title 
Innløpet – flyt for brevkode Ferdigstilte journalposter
end title           
[*]-->MottattType
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> KategoriseringType
KategoriseringType --> AvventerGosysType
AvventerGosysType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
note left of InnsendingFerdigstiltType
Kategorisert som: UkjentSkjemaKode
Behandlende enhet: 4450  
end note
@enduml