@startuml
title 
Innløpet – flyt for brevkode GENERELL_INNSENDING
end title           
[*]-->MottattType
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> KategoriseringType
KategoriseringType --> AvventerSøknadsdataType
AvventerSøknadsdataType --> AventerArenaOppgaveType
AventerArenaOppgaveType --> AvventerFerdigstillJournalpostType
AvventerFerdigstillJournalpostType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
note left of InnsendingFerdigstiltType
Kategorisert som: Generell
Behandlende enhet: 4450  
end note
@enduml