@startuml
title 
Innløpet – flyt for brevkode GENERELL_INNSENDING
end title           
[*]-->MottattType 
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> KategoriseringType
KategoriseringType --> AvventerSøknadsdataType
AvventerSøknadsdataType --> AventerArenaOppgaveType
AventerArenaOppgaveType --> AvventerFerdigstillJournalpostType
AvventerFerdigstillJournalpostType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
@enduml