@startuml
title 
Innløpet – flyt for brevkode NAV 04-06.05
end title           
[*]-->MottattType
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> KategoriseringType
KategoriseringType --> AventerArenaOppgaveType
AventerArenaOppgaveType --> AvventerFerdigstillJournalpostType
AvventerFerdigstillJournalpostType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
note left of InnsendingFerdigstiltType
Kategorisert som: Utdanning
Behandlende enhet: 4450  
end note
@enduml