@startuml
title 
Innløpet – flyt for brevkode NAV 04-01.03
end title           
[*]-->MottattType
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> KategoriseringType
KategoriseringType --> AvventerSøknadsdataType
AvventerSøknadsdataType --> AvventerMinsteinntektVurderingType
AvventerMinsteinntektVurderingType --> AvventerSvarOmEksisterendeSakerType
AvventerSvarOmEksisterendeSakerType --> AventerArenaStartVedtakType
AventerArenaStartVedtakType --> AvventerFerdigstillJournalpostType
AvventerFerdigstillJournalpostType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
note left of InnsendingFerdigstiltType
Kategorisert som: NySøknad
Behandlende enhet: 4450  
end note
@enduml