@startuml
title 
Innløpet – flyt for brevkode NAV 90-00.08-feriepenger
end title           
[*]-->MottattType 
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> KategoriseringType
KategoriseringType --> AventerArenaOppgaveType
AventerArenaOppgaveType --> AvventerFerdigstillJournalpostType
AvventerFerdigstillJournalpostType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
@enduml