@startuml
title 
Innløpet – flyt for brevkode NAVe 04-01.04
end title           
[*]-->MottattType
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> KategoriseringType
KategoriseringType --> AvventerSøknadsdataType
AvventerSøknadsdataType --> AventerArenaOppgaveType
AventerArenaOppgaveType --> AvventerFerdigstillJournalpostType
AvventerFerdigstillJournalpostType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
note left of InnsendingFerdigstiltType
Kategorisert som: Ettersending
Behandlende enhet: 4450  
end note
@enduml