@startuml
title 
Innløpet – flyt for brevkode Ukjente brevkoder
end title           
[*]-->MottattType 
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> KategoriseringType
KategoriseringType --> AvventerGosysType
AvventerGosysType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
@enduml