@startuml
title 
Innløpet – flyt for brevkode Ukjent bruker
end title           
[*]-->MottattType
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> UkjentBrukerType
UkjentBrukerType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
note left of InnsendingFerdigstiltType
Kategorisert som: Ettersending
Behandlende enhet: 4450  
end note
@enduml