@startuml
title 
Innløpet – flyt for brevkode Ukjent bruker ab0451
end title           
[*]-->MottattType 
MottattType --> AvventerJournalpostType
AvventerJournalpostType --> AvventerPersondataType
AvventerPersondataType --> UkjentBrukerType
UkjentBrukerType --> InnsendingFerdigstiltType
InnsendingFerdigstiltType--> [*]
@enduml